---
title: "Initial EDA Basic Outline"
author: "Sangeeta Iyer"
output: html_notebook
---
```
# load necessary packages
library(tidyverse)
library(mosaic)
library(esquisse)
```
This is an outline for your Initial EDA. You can follow this outline, or you can modify it as you see fit. Do what works best for your project. 

## Research Question 

State your specific research question and why it is interesting. 
I want to investigate the correlation between government makeup (as in political party) of each state and rate of bill passage. This is interesting because state legislatures are often overlooked, yet the bills they pass affect their citizens' lives more potently. Especially in the recent American political climate, as the power of the national government is being limited, state legislatures have more control over hot button topics, such as abortion access. Therefore, I want to look into whether or not the makeup of the state government has any impact on the rate of bill passage, as this could influence strategic campaign decisions.



## Data Processing 

#### Data Intake 

Include R code and written explanation to import your **TWO** data sets.

#### Data Wrangling 

Include R code and written explanation for wangling your data (you can make multiple wrangled data sets). 




## Data Visualization

#### Plot 1

Include R code to make one data visualization (I would encourage you to use 3 or more variables). Include a brief written description of what your graph shows. Is this graph helpful in answering your research question? If it is helpful, will you need to add/modify anything in this graph in the final report? 

#### Plot 2

Include R code to make one data visualization (I would encourage you to use 3 or more variables). Include a brief written description of what your graph shows. Is this graph helpful in answering your research question? If it is helpful, will you need to add/modify anything in this graph in the final report? 


## Conclusion

Include your initial intuition as to what the answer to your research question is using the data sets and visualizations you created. 
